before:
  hooks:
    - go mod tidy -go=1.16 && go mod tidy -go=1.17
    - find . -type f -name "*.go" | xargs addlicense -c "IBM Corporation."
env:
  - CGO_ENABLED=0
builds:
  - id: datactl
    main: ./cmd/datactl
    binary: oc-datactl
    flags:
      - -tags=prod
    hooks:
      pre: sh -c "echo 'version={{ .Version }} sha={{ .ShortCommit }} date={{ .Date }}' > ./cmd/datactl/app/version.txt"
    goos:
      - darwin
      - windows
    goarch:
      - amd64
  - id: datactl-arm64
    main: ./cmd/datactl
    binary: oc-datactl
    flags:
      - -tags=prod
    hooks:
      pre: sh -c "echo 'version={{ .Version }} sha={{ .ShortCommit }} date={{ .Date }}' > ./cmd/datactl/app/version.txt"
    goos:
      - darwin
      - linux
    goarch:
      - arm64
  - id: datactl-otherarch
    main: ./cmd/datactl
    binary: oc-datactl
    flags:
      - -tags=prod
    hooks:
      pre: sh -c "echo 'version={{ .Version }} sha={{ .ShortCommit }} date={{ .Date }}' > ./cmd/datactl/app/version.txt"
    goos:
      - linux
    goarch:
      - amd64
      - s390x
      - ppc64le
archives:
  - id: tar
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
    builds:
      - datactl
      - datactl-arm64
      - datactl-otherarch
    format: tar.gz
    files:
      - LICENSE
      - src: './docs/*.md'
        dst: docs
        strip_parent: true
      - src: './hack/service-account-role.yaml'
        dst: resources
        strip_parent: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
