apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhm-files
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - nonResourceURLs: ['/v1/files', '/v1/files/*']
    verbs: ['get']
  - nonResourceURLs: ['/v1/files/*']
    verbs: ['delete', 'update']
  - nonResourceURLs: ['/v1/file/*']
    verbs: ['create']
