name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.13

      - name: Build
        run: go build -v ./...

      - name: WhiteSource Unified Agent Scan
        env:
          WS_APIKEY: ${{secrets.WS_APIKEY}}
          WS_USERKEY: ${{secrets.WS_USERKEY}}
          WS_WSS_URL: https://ibmets.whitesourcesoftware.com/agent
          WS_PRODUCTNAME: PSIRT_PRD0011140
          WS_PROJECTNAME: ${{github.event.repository.name}}
        run: |
          echo Downloading WhiteSource Unified Agent
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
            echo "Integrity Check Failed"
          else
            echo "Integrity Check Passed"
            echo Starting WhiteSource Scan
            java -jar wss-unified-agent.jar
          fi

      - name: Ginkgo
        run: |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega/...

      - name: Test
        run: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: github.ref != 'refs/heads/main'
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist

      - name: Archive build
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/**/*.tar.gz
